FROM postgres:15

ARG UID=1000
ARG GID=1000


RUN groupadd -g ${GID} postgres && \
    useradd -u ${UID} -g postgres postgres && \
    mkdir -p /var/lib/postgresql/data && \
    chown -R postgres:postgres /var/lib/postgresql/data

USER postgres
