services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PYTHONWARNINGS=ignore
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - my-network
    restart: unless-stopped
    user: "5050:5050"
    depends_on:  # ОДИН depends_on
      postgres-db:
        condition: service_healthy
    entrypoint: >
      sh -c "
      chown -R 5050:5050 /var/lib/pgadmin &&
      chmod -R 755 /var/lib/pgadmin &&
      exec /entrypoint.sh
      "

  django:
    build:
      context: .
      args:
        UID: ${UID:-1000} # Take UID from environment else use 1000
        GID: ${GID:-1000} # Take GID from environment else use 1000
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECRET_KEY=bla312()819203812903uriohsdgjk
      - PYTHONUNBUFFERED=1
      - DEBUG=false
    networks:
      - my-network
    depends_on:
      postgres-db:
        condition: service_healthy
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      sh -c "
      echo 'Проверка прав доступа...' &&
      touch /app/test_write && rm /app/test_write &&
      echo 'Права на запись есть' &&
      echo 'Ожидание PostgreSQL...' &&
      python wait_for_db.py &&
      echo 'Применение миграций...' &&
      python manage.py migrate &&
      echo 'Запуск сервера...' &&
      python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

networks:
  my-network:
    driver: bridge
