services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    user: "${MY_UID:-1000}:${MY_GID:-1000}"  # Используем MY_UID

  django:
    build:
      context: .
      args:
        UID: ${MY_UID:-1000}  # Передаем как UID в Dockerfile
        GID: ${MY_GID:-1000}
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECRET_KEY=bla312()819203812903uriohsdgjk
      - PYTHONUNBUFFERED=1
      - DEBUG=false
    networks:
      - my-network
    depends_on:
      postgres-db:
        condition: service_healthy
    user: "${MY_UID:-1000}:${MY_GID:-1000}"  # Используем MY_UID
    command: >
      sh -c "
      echo 'Ожидание PostgreSQL...' &&
      python wait_for_db.py &&
      echo 'Применение миграций...' &&
      python manage.py makemigrations api &&
      python manage.py migrate &&
      echo 'Запуск сервера...' &&
      python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

networks:
  my-network:
    driver: bridge
