# Generated by Django 6.0.2 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Название рубрики')),
                ('counter', models.IntegerField(default=0, help_text='Количество элементов в рубрике', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
    ]
