# Generated by Django 6.0.2 on 2026-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве'), ('check', 'На рассмотрении')], default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
