# Generated by Django 6.0.3 on 2026-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве'), ('check', 'На рассмотрении'), ('banned', 'Забанен')], default='published', max_length=20, verbose_name='Статус'),
        ),
    ]
