# Generated by Django 6.0.3 on 2026-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rubrics/', verbose_name='Фото рубрики'),
        ),
    ]
