# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_options_post_author_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(
                blank=True,
                help_text='Адрес инцидента/события',
                max_length=500,
                verbose_name='Адрес события'
            ),
        ),
    ]
