# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(
                blank=True,
                help_text='Latitude: -90 до 90',
                null=True,
                verbose_name='Широта'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(
                blank=True,
                help_text='Longitude: -180 до 180',
                null=True,
                verbose_name='Долгота'
            ),
        ),
    ]
