# Generated by Django 6.0.3 on 2026-03-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_status'),
        ('api', '0007_post_latitude_post_longitude'),
    ]

    operations = [
    ]
